Bwr.WebApp/Controllers/Client/ClientCashController.cs
using BWR.Application.Interfaces.Client;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bwr.WebApp.Controllers.Client
{
    public class ClientCashController : Controller
    {
        private readonly IClientCashAppService _clientCashAppService;

        public ClientCashController(IClientCashAppService clientCashAppService)
        {
            _clientCashAppService = clientCashAppService;
        }
        // GET: ClientCash
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetClientCashes(int clientId, int coinId)
        {
            var clientCashes = _clientCashAppService.GetAll().FirstOrDefault(x => x.ClientId == clientId && x.CoinId == clientId);

            return Json(clientCashes);
        }
    }
}

Bwr.WebApp/Controllers/Client/ClientController.cs
using BWR.Application.Interfaces.Setting;
using BWR.ShareKernel.Exceptions;
using System.Linq;
using System.Linq.Dynamic;
using System.Web.Mvc;
using BWR.Infrastructure.Exceptions;
using DataTables.Mvc;
using BWR.Application.Dtos.Client;
using BWR.Application.Interfaces.Client;
using System.Collections.Generic;
using AutoMapper;
using BWR.Domain.Model.Clients;
using System;
using BWR.Application.Interfaces.Shared;
using System.IO;
using BWR.Application.Extensions;

namespace Bwr.WebApp.Controllers
{
    public class ClientController : Controller
    {
        private readonly IClientAppService _clientAppService;
        private readonly IClientAttatchmentAppService _clientAttatchmentAppService;
        private readonly IProvinceAppService _provinceAppService;
        private readonly IAppSession _appSession;
        private string _message;
        private bool _success;

        public ClientController(
            IClientAppService clientAppService, 
            IProvinceAppService provinceAppService, 
            IClientAttatchmentAppService clientAttatchmentAppService, 
            IAppSession appSession)
        {
            _clientAppService = clientAppService;
            _provinceAppService = provinceAppService;
            _clientAttatchmentAppService = clientAttatchmentAppService;
            _appSession = appSession;
            _message = "";
            _success = false;
        }

        public ActionResult Index()
        {
            return View();
        }

        #region Client

        public ActionResult Get([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {
            try
            {
                var clients = _clientAppService.GetAll().AsQueryable();

                var totalCount = clients.Count();

                // searching and sorting
                clients = SearchAndSort(requestModel, clients);
                var filteredCount = clients.Count();

                // Paging
                clients = clients.Skip(requestModel.Start).Take(requestModel.Length);

                var dataTablesResponse = new DataTablesResponse(requestModel.Draw, clients.ToList(), filteredCount, totalCount);
                return Json(dataTablesResponse, JsonRequestBehavior.AllowGet);
            }
            catch (BwrException ex)
            {
                Tracing.SaveException(ex);
                return Json(new { Success = false, Message = _message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetClientById(int clientId)
        {
            var client = _clientAppService.GetById(clientId);

            return Json(new { client.Address, Phone = client.GetFirstPhone() });
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View("_CreateClient");
        }

        [HttpPost]
        public ActionResult Create(ClientInsertDto dto)
        {
            if (ChechIfPhoneRepeated(dto.ClientPhones))
            {
                _success = false;
                _message = "رقم الهاتف مكرر";
            }
            else
            {
                dto.ClientType = ClientType.Client;
                var clientDto = _clientAppService.Insert(dto);
                if (clientDto != null)
                    _success = true;
                else
                {
                    _success = false;
                    _message = "حدثت مشكلة اثناء إضافة بيانات العميل";
                }
            }

            return Json(new { Success = _success, Message = _message }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var dto = _clientAppService.GetForEdit(id);

            if (Request.IsAjaxRequest())
                return PartialView("_EditClient", dto);

            return View(dto);
        }

        [HttpPost]
        public ActionResult Edit(ClientUpdateDto dto)
        {
            if (ChechIfPhoneRepeated(dto.ClientPhones))
            {
                _success = false;
                _message = "رقم الهاتف مكرر";
            }
            else
            {
                var clientDto = _clientAppService.Update(dto);
                if (clientDto != null)
                    _success = true;
                else
                {
                    _success = false;
                    _message = "حدثت مشكلة اثناء تعديل بيانات العميل";
                }
            }

            return Json(new { Success = _success, Message = _message }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var dto = _clientAppService.GetById(id);

            if (Request.IsAjaxRequest())
                return PartialView("_DeleteClient", dto);

            return View(dto);
        }

        [HttpPost]
        public ActionResult Delete(ClientDto dto)
        {
            _clientAppService.Delete(dto.Id.Value);

            return Content("success");
        }

        public ActionResult Detail(int id)
        {
            var dto = _clientAppService.GetById(id);

            if (Request.IsAjaxRequest())
                return PartialView("_DetailsClient", dto);

            return View(dto);
        }
        
        #endregion

        public ActionResult UpdateAddressAndPhoneNumberIfNotExist(int clientId, string phone, string address)
        {
            try
            {
                bool isUpdated = false;
                var client = _clientAppService.GetById(clientId);
                if (client != null)
                {
                    if (client.Address.Trim() != address.Trim())
                    {
                        isUpdated = true;
                        client.Address = address;
                    }
                    if (client.ClientPhones.Any(x => x.Phone.Trim().Equals(phone.Trim())))
                    {
                        isUpdated = true;
                        var clientPhoneDto = new ClientPhoneDto()
                        {
                            Phone = phone,
                            ClientId = client.Id.Value,
                            IsEnabled = true
                        };
                        client.ClientPhones.Add(clientPhoneDto);

                    }
                    if (isUpdated)
                    {
                        var clientUpdateDto = Mapper.Map<ClientDto, ClientUpdateDto>(client);
                        _clientAppService.Update(clientUpdateDto);
                    }
                }

                _success = true;
            }
            catch (BwrException ex)
            {
                _success = false;
                _message = "حدثت مشكلة اثناء التعديل على معلومات العميل";
            }


            return Json(new { Success = _success, Message = _message }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult UpdatePhoneNumberIfNotExist(int clientId, string phone)
        {
            try
            {
                var client = _clientAppService.GetById(clientId);
                if (client != null)
                {
                    if (client.ClientPhones.Any(x => x.Phone.Trim().Equals(phone.Trim())))
                    {
                        var clientPhoneDto = new ClientPhoneDto()
                        {
                            Phone = phone,
                            ClientId = client.Id.Value,
                            IsEnabled = true
                        };
                        client.ClientPhones.Add(clientPhoneDto);
                        var clientUpdateDto = Mapper.Map<ClientDto, ClientUpdateDto>(client);
                        _clientAppService.Update(clientUpdateDto);

                    }
                }

                _success = true;
            }
            catch (BwrException ex)
            {
                _success = false;
                _message = "حدثت مشكلة اثناء التعديل على معلومات العميل";
            }

            return Json(new { Success = _success, Message = _message }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult AddNewClientFroTransaction()
        {
            var fullName = Request.Params["fullName"];
            var phone = Request.Params["Phone"];
            var address = Request.Params["address"];
            try
            {
                var clientInsertDto = new ClientInsertDto()
                {
                    FullName = fullName,
                    IsEnabled = true,
                    Address = address,
                    ClientType = ClientType.Normal
                    
                };

                var clientDto = _clientAppService.Insert(clientInsertDto);

                var clientPhoneDto = new ClientPhoneDto()
                {
                    Phone = phone,
                    IsEnabled=true,
                     ClientId= clientDto.Id.Value
                };

                var clientUpdateDto = Mapper.Map<ClientDto, ClientUpdateDto>(clientDto);
                clientUpdateDto.ClientPhones.Add(clientPhoneDto);
                _clientAppService.Update(clientUpdateDto);

                var files = Request.Files;
                if (files.Count > 0)
                {
                    int imageType = 0; ;
                    try
                    {
                        imageType = Convert.ToInt32(Request.Params["imageType"]);
                    }
                    catch
                    {                     
                    }
                    if (imageType != 0 && files != null)
                    {
                        var file = files[0];
                        string extension = @Path.GetExtension(file.FileName);
                        string fileName = ((long)(DateTime.Now - DateTime.MinValue).TotalMilliseconds).ToString() + extension;

Bwr.WebApp/Controllers/Setting/CoinController.cs
using BWR.Application.Dtos.Setting.Coin;
using BWR.Application.Interfaces.Setting;
using BWR.Infrastructure.Exceptions;
using BWR.ShareKernel.Exceptions;
using DataTables.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;

namespace Bwr.WebApp.Controllers.Setting
{
    public class CoinController : Controller
    {
        private readonly ICoinAppService _coinAppService;
        private string _message;
        private bool _success;

        public CoinController(ICoinAppService coinAppService)
        {
            _coinAppService = coinAppService;
            _message = "";
            _success = false;
        }

        public ActionResult Index()
        {
            return View();
        }

        #region Coin

        public ActionResult Get([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {
            try
            {
                var coins = _coinAppService.GetAll().AsQueryable();

                var totalCount = coins.Count();

                // searching and sorting
                coins = SearchAndSort(requestModel, coins);
                var filteredCount = coins.Count();

                // Paging
                coins = coins.Skip(requestModel.Start).Take(requestModel.Length);

                var dataTablesResponse = new DataTablesResponse(requestModel.Draw, coins.ToList(), filteredCount, totalCount);
                return Json(dataTablesResponse, JsonRequestBehavior.AllowGet);
            }
            catch (BwrException ex)
            {
                Tracing.SaveException(ex);
                return Json(new { Success = false, Message = _message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetCoinsForDropdown(string term)
        {
            var coins = _coinAppService.GetForDropdown(term);

            return Json(new { Coins = coins }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSpecificCoin(string name, int? id)
        {

            try
            {
                var coin = new CoinForDropdownDto();
                if (id != null)
                    coin = _coinAppService.GetForDropdown(name).FirstOrDefault(x => x.Id != id);
                else
                    coin = _coinAppService.GetForDropdown(name).FirstOrDefault();

                return Json(new { Success = true, Coin = coin }, JsonRequestBehavior.AllowGet);
            }
            catch (BwrException ex)
            {
                Tracing.SaveException(ex);
                return Json(new { Success = false, Message = _message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View("_CreateCoin");
        }

        [HttpPost]
        public ActionResult Create(CoinInsertDto dto)
        {
            var exist = false;

            if (_coinAppService.CheckIfExist(dto.Name, 0))
            {
                _success = false;
                _message = "توجد عملة بنفس الاسم";
                exist = true;
            }
            else
            {
                var coinDto = _coinAppService.Insert(dto);
                if (coinDto != null)
                    _success = true;
                else
                {
                    _success = false;
                    _message = "حدثت مشكلة اثناء إضافة بيانات العملة";
                }
            }

            return Json(new { Success = _success, Message = _message, Exist = exist }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var dto = _coinAppService.GetForEdit(id);

            if (Request.IsAjaxRequest())
                return PartialView("_EditCoin", dto);

            return View(dto);
        }

        [HttpPost]
        public ActionResult Edit(CoinUpdateDto dto)
        {
            var exist = false;

            if (_coinAppService.CheckIfExist(dto.Name, dto.Id.Value))
            {
                _success = false;
                _message = "توجد عملة بنفس الاسم";
                exist = true;
            }
            else
            {
                var coinDto = _coinAppService.Update(dto);
                if (coinDto != null)
                    _success = true;
                else
                {
                    _success = false;
                    _message = "حدثت مشكلة اثناء تعديل بيانات العملة";
                }
            }

            return Json(new { Success = _success, Message = _message, Exist = exist }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var dto = _coinAppService.GetById(id);

            if (Request.IsAjaxRequest())
                return PartialView("_DeleteCoin", dto);

            return View(dto);
        }

        [HttpPost]
        public ActionResult Delete(CoinDto dto)
        {
            _coinAppService.Delete(dto.Id.Value);

            return Content("success");
        }

        public ActionResult Detail(int id)
        {
            var dto = _coinAppService.GetById(id);

            if (Request.IsAjaxRequest())
                return PartialView("_DetailsCoin", dto);

            return View(dto);
        }

        #endregion

        

        #region Helper Method

        private IQueryable<CoinDto> SearchAndSort(IDataTablesRequest requestModel, IQueryable<CoinDto> query)
        {
            // Apply filters
            if (requestModel.Search.Value != string.Empty)
            {
                var value = requestModel.Search.Value.Trim();
                query = query.Where(p => p.Name.Contains(value) ||
                                   p.Code.Contains(value) 

                                   );
            }

            var filteredCount = query.Count();

            // Sort
            var sortedColumns = requestModel.Columns.GetSortedColumns();
            var orderByString = string.Empty;

            foreach (var column in sortedColumns)
            {
                orderByString += orderByString != string.Empty ? "," : "";
                orderByString += (column.Data) + (column.SortDirection == Column.OrderDirection.Ascendant ? " asc" : " desc");
            }

            query = query.OrderBy(orderByString == string.Empty ? "BarCode asc" : orderByString);

            return query;
        }

        #endregion
    }
}

Bwr.WebApp/Views/Client/_CreateClient.cshtml
@model BWR.Application.Dtos.Client.ClientInsertDto
@{

    Layout = null;
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">إضافة عميل</h4>
        </div>
        @using (Ajax.BeginForm("Create", "Client", null, new AjaxOptions { HttpMethod = "Post", OnSuccess = "createClientSuccess" }, new { @class = "form-horizontal", role = "form", id = "addClientForm" }))
        {
            <div class="modal-body ">
                <div class="col-lg-12 col-md-12">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item active">
                            
                            <a class="nav-link active" id="client-tab" data-toggle="tab" href="#addClientSection" role="tab">بيانات العميل</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="phones-tab" data-toggle="tab" href="#addPhoneSection" role="tab">الهواتف</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="cashFlow-tab" data-toggle="tab" href="#addClientCashFlow" role="tab">الرصيد</a>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-12 col-md-12">
                    <div class="tab-content">
                        <div class="tab-pane active" id="addClientSection">
                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-group">
                                    <label class="control-label col-md-3" for="Name">اسم العميل <span class="text-danger">*</span></label>
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control", id = "a-client-fullName" } })

                                        @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-3" for="CompanyCountries">اختر المنطقة<span class="text-danger">*</span></label>
                                    <div class="col-md-9">
                                        @Html.DropDownListFor(model => model.CountryId, new List<SelectListItem>(), new { @class = "form-control", id = "a-client-countryId" })
                                        <span class="text-danger field-validation-error" data-valmsg-for="CountryId" data-valmsg-replace="true"></span>
                                    </div>

                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-3" for="Name">العنوان التفصيلي <span class="text-danger">*</span></label>
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", id = "a-client-address" } })

                                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="control-label col-md-3" for="Name">الحساب فعال </label>
                                    <div class="col-md-9">
                                        <div class="checkbox">
                                            <label>
                                                @Html.EditorFor(model => model.IsEnabled, new { htmlAttributes = new { @class = "flat", id = "a-client-isEnabled" } })
                                            </label>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>

                        <div class="tab-pane" id="addPhoneSection">
                            <div class="row">
                                <div class="col-sm-4 col-sm-4"></div>

                                <div class="col-md-4 col-sm-4">
                                    <h4>إضافة ارقام الهواتف</h4>
                                </div>
                            </div>

                            <div style="margin-bottom:10px;"></div>

                            <div class="row">
                                <div class="col-md-8">
                                    <button type="button" class="btn btn-success" id="addPhoneTextBtn">إضافة حقل جديد <span class="fa fa-plus"></span></button>
                                </div>
                            </div>
                            <div style="margin-bottom:10px;"></div>
                            <div class="row">
                                <div class="col-md-3 col-sm-3"></div>
                                <div class="col-md-8 col-sm-8">
                                    <div class="row a-phone-group">



                                    </div>
                                </div>
                            </div>

                            <div style="margin-bottom:15px;"></div>
                        </div>

                        <div id="addClientCashFlow" class="tab-pane">
                            <div class="row a-coins">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">

                        <button id="btnAddClient" type="button" class="btn btn-primary">حفظ <span class="glyphicon glyphicon-save"></span></button>
                        <button type="button" class="btn btn-sm btn-default" onclick="resetAddClientContainer();" data-dismiss="modal">إغلاق <span class="glyphicon glyphicon-remove"></span></button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script>
    var aTable;
    var oldData;
    $(function () {

        $('input.flat').iCheck({
            checkboxClass: 'icheckbox_flat-green',
            radioClass: 'iradio_flat-green'
        });

        initialCountries();
        initialCoins();

        var $form = $("#addClientForm");
        $.validator.unobtrusive.parse($form);

        $('#btnAddClient').on("click", function (event) {
            if ($form.valid()) {
                var dto = {
                    FullName: $('#a-client-fullName').val(),
                    Address: $('#a-client-address').val(),
                    ClientPhones: getPhonesValues(),
                    ClientCashes: getCoins(),
                    IsEnabled: getIsEnableValue(),
                    CountryId: getSelectedCountry()
                };

                $.ajax({
                    url: '@Url.Action("Create", "Client")',
                    type: 'POST',
                    data: dto,
                    dataType: "json",
                    cache: false,
                    success: function (data) {

                        if (data.Success == true) {
                            $('#createClientModal').modal('hide');
                            $('#createClientContainer').html('');

                            $clientDataTable.refresh();
                            toastr.success('تم الحفظ بنجاح')
                        }
                        else {
                            alert(data.Message);
                            toastr.error(data.Message);
                        }

                    },
                    error: function () { toastr.error("خدث خطأ ما أثناء الإضافة"); }
                });

            }


        });

        initNewPhoneEle();

        $('#addPhoneTextBtn').click(function () {
            addPhoneTextELement();
        });

    });

    //===Initial Functions===//
    
    function initNewPhoneEle() {
        $('.a-phone-group').append(getHtml());
    }

    function addPhoneTextELement() {

        var isEmpty = false;
        $('.a-phone-group :input.a-phone-input').each(function (data) {

            var value = $(this).val();
            if (value.trim() == "") {
                isEmpty = true;
                return;
            }
        });

        if (!isEmpty) {
            $('.a-phone-group').append(getHtml());

            //remove copy value from new textbox
            $('.a-phone-group :input.a-phone-input').last().val("")
        }

    }

    function initialCountries() {
         $.get('@Url.Action("GetAllWithProvinces", "Country")', function (data) {

             var countries = data.Countries;

             var option = '<option index="0"></option>';
             $('#a-client-countryId').append(option);

            for (var i = 0; i < countries.length; i++) {
                var option = '<option value="' + countries[i].Id + '">' + countries[i].Name + '</option>';
                $('#a-client-countryId').append(option);
            }

             $('#a-client-countryId').select2({ width: null, placeholder: "اختر منطقة" });

             //$("#a-client-countryId").select2("val", "");
             $('#a-client-countryId').val('').trigger('change')

        });
    }

    function initialCoins() {
        $.get('@Url.Action("GetCoinsForDropdown","Coin")', { term: "" }, function (data) {

            var coins = data.Coins;
            for (var i = 0; i < coins.length; i++) {
                var ele = '<div class="form-group">' +
                    '<label class="control-label col-md-3 col-sm-3">' + coins[i].Name + ':</label>' +
                    '<div class="col-md-8 col-sm-8">' +
                    '<div class="input-group">' +
                    '<input  type="number" data-coin-id="' + coins[i].Id+'" class="form-control a-coins-inputs" value="0" />' +
                    '<span class="input-group-addon">' + coins[i].Code + '</span>' +

                    '</div>' +
                    '</div>' +
                    '</div>';

                $('.a-coins').append(ele);
            }
            
        });
    }

    //===Get Functions===//

    function getPhonesValues() {
        var phones = [];
        
        $('.a-phone-group :input.a-phone-input').each(function (data) {

            var value = $(this).val();
            if (value.trim() != "" && value != null) {

                phones.push({ 'Phone': value.trim(), 'IsEnabled': true });
            }
        });

        return phones;
    }

    function getHtml() {
        return '<div class="col-md-8 col-sm-8 a-phone" style="margin-bottom:5px;">' +
            '<div class="input-group">' +
            '<input type="text" date-phone-id="0" placeholder="ادخل رقم الهاتف" class="form-control has-error a-phone-input" value="" />' +
            '<span class="input-group-addon" onclick="this.parentElement.parentElement.remove();"><span class="fa fa-close"></span></span>' +
            '</div > ' +
            '</div >';
    }

    function getIsEnableValue() {
        var divChecked = $('#IsEnabled').parent();
        if (divChecked.hasClass('checked'))
            return true;
        else
            return false;
    }

    function getSelectedCountry() {
        
        var data = $('#a-client-countryId').select2('data');
        return data[0].id;
    }

    function getCoins() {
       
        var companyCoins = [];
        var coinInputs = $('.a-coins-inputs');
        for (var i = 0; i < coinInputs.length; i++) {
            var id = $(coinInputs[i]).attr('data-coin-id');
            var value = $(coinInputs[i]).val();

            companyCoins.push({ 'InitialBalance': value, 'Total': value, 'CoinId': id });
        }

        return companyCoins;
    }

    //===Other Functions===//

    function resetAddClientContainer() {

        $('#createClientModal').modal('hide');
        $('#createClientContainer').html('');
    }

</script>