Bwr.WebApp/Controllers/Setting/CoinController.cs
using BWR.Application.Dtos.Setting.Coin;
using BWR.Application.Interfaces.Setting;
using BWR.Infrastructure.Exceptions;
using BWR.ShareKernel.Exceptions;
using DataTables.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;

namespace Bwr.WebApp.Controllers.Setting
{
    public class CoinController : Controller
    {
        private readonly ICoinAppService _coinAppService;
        private string _message;
        private bool _success;

        public CoinController(ICoinAppService coinAppService)
        {
            _coinAppService = coinAppService;
            _message = "";
            _success = false;
        }

        public ActionResult Index()
        {
            return View();
        }

        #region Coin

        public ActionResult Get([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {
            try
            {
                var coins = _coinAppService.GetAll().AsQueryable();

                var totalCount = coins.Count();

                // searching and sorting
                coins = SearchAndSort(requestModel, coins);
                var filteredCount = coins.Count();

                // Paging
                coins = coins.Skip(requestModel.Start).Take(requestModel.Length);

                var dataTablesResponse = new DataTablesResponse(requestModel.Draw, coins.ToList(), filteredCount, totalCount);
                return Json(dataTablesResponse, JsonRequestBehavior.AllowGet);
            }
            catch (BwrException ex)
            {
                Tracing.SaveException(ex);
                return Json(new { Success = false, Message = _message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetCoinsForDropdown(string term)
        {
            var coins = _coinAppService.GetForDropdown(term);

            return Json(new { Coins = coins }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSpecificCoin(string name, int? id)
        {

            try
            {
                var coin = new CoinForDropdownDto();
                if (id != null)
                    coin = _coinAppService.GetForDropdown(name).FirstOrDefault(x => x.Id != id);
                else
                    coin = _coinAppService.GetForDropdown(name).FirstOrDefault();

                return Json(new { Success = true, Coin = coin }, JsonRequestBehavior.AllowGet);
            }
            catch (BwrException ex)
            {
                Tracing.SaveException(ex);
                return Json(new { Success = false, Message = _message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View("_CreateCoin");
        }

        [HttpPost]
        public ActionResult Create(CoinInsertDto dto)
        {
            var exist = false;

            if (_coinAppService.CheckIfExist(dto.Name, 0))
            {
                _success = false;
                _message = "توجد عملة بنفس الاسم";
                exist = true;
            }
            else
            {
                var coinDto = _coinAppService.Insert(dto);
                if (coinDto != null)
                    _success = true;
                else
                {
                    _success = false;
                    _message = "حدثت مشكلة اثناء إضافة بيانات العملة";
                }
            }

            return Json(new { Success = _success, Message = _message, Exist = exist }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var dto = _coinAppService.GetForEdit(id);

            if (Request.IsAjaxRequest())
                return PartialView("_EditCoin", dto);

            return View(dto);
        }

        [HttpPost]
        public ActionResult Edit(CoinUpdateDto dto)
        {
            var exist = false;

            if (_coinAppService.CheckIfExist(dto.Name, dto.Id.Value))
            {
                _success = false;
                _message = "توجد عملة بنفس الاسم";
                exist = true;
            }
            else
            {
                var coinDto = _coinAppService.Update(dto);
                if (coinDto != null)
                    _success = true;
                else
                {
                    _success = false;
                    _message = "حدثت مشكلة اثناء تعديل بيانات العملة";
                }
            }

            return Json(new { Success = _success, Message = _message, Exist = exist }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var dto = _coinAppService.GetById(id);

            if (Request.IsAjaxRequest())
                return PartialView("_DeleteCoin", dto);

            return View(dto);
        }

        [HttpPost]
        public ActionResult Delete(CoinDto dto)
        {
            _coinAppService.Delete(dto.Id.Value);

            return Content("success");
        }

        public ActionResult Detail(int id)
        {
            var dto = _coinAppService.GetById(id);

            if (Request.IsAjaxRequest())
                return PartialView("_DetailsCoin", dto);

            return View(dto);
        }

        #endregion

        

        #region Helper Method

        private IQueryable<CoinDto> SearchAndSort(IDataTablesRequest requestModel, IQueryable<CoinDto> query)
        {
            // Apply filters
            if (requestModel.Search.Value != string.Empty)
            {
                var value = requestModel.Search.Value.Trim();
                query = query.Where(p => p.Name.Contains(value) ||
                                   p.Code.Contains(value) 

                                   );
            }

            var filteredCount = query.Count();

            // Sort
            var sortedColumns = requestModel.Columns.GetSortedColumns();
            var orderByString = string.Empty;

            foreach (var column in sortedColumns)
            {
                orderByString += orderByString != string.Empty ? "," : "";
                orderByString += (column.Data) + (column.SortDirection == Column.OrderDirection.Ascendant ? " asc" : " desc");
            }

            query = query.OrderBy(orderByString == string.Empty ? "BarCode asc" : orderByString);

            return query;
        }

        #endregion
    }
}

Bwr.WebApp/Controllers/Treasury/TreasuryCashController.cs
using BWR.Application.Dtos.Treasury;
using BWR.Application.Interfaces.Treasury;
using BWR.Infrastructure.Exceptions;
using BWR.ShareKernel.Exceptions;
using DataTables.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bwr.WebApp.Controllers.Treasury
{
    public class TreasuryCashController : Controller
    {
        private readonly ITreasuryCashAppService _treasuryCashAppService;
        public TreasuryCashController(ITreasuryCashAppService treasuryCashAppService)
        {
            _treasuryCashAppService = treasuryCashAppService;
        }

        
        public ActionResult Index(int treasuryId)
        {

            return View();
        }

        // GET: TreasuryCashFlow
        public ActionResult Get(int treasuryId)
        {
            var treasuryCashes = _treasuryCashAppService.GetTreasuryCashes(treasuryId);
            return Json(new { data = treasuryCashes }, JsonRequestBehavior.AllowGet);
        }

        
    }
}

Bwr.WebApp/Controllers/Treasury/TreasuryController.cs
using BWR.Application.Dtos.Treasury;
using BWR.Application.Interfaces.Treasury;
using BWR.Application.Interfaces.Setting;
using BWR.Infrastructure.Exceptions;
using BWR.ShareKernel.Exceptions;
using DataTables.Mvc;
using System.Linq;
using System.Linq.Dynamic;
using System.Web.Mvc;

namespace Bwr.WebApp.Controllers
{
    public class TreasuryController : Controller
    {
        private readonly ITreasuryAppService _treasuryAppService;
        private readonly ITreasuryCashAppService _treasuryCashAppService;
        private readonly ICoinAppService _coinAppService;
        private string _message;
        private bool _success;

        public TreasuryController(
            ITreasuryAppService treasuryAppService,
            ITreasuryCashAppService treasuryCashAppService,
            ICoinAppService coinAppService)
        {
            _treasuryAppService = treasuryAppService;
            _treasuryCashAppService = treasuryCashAppService;
            _coinAppService = coinAppService;

            _message = "";
            _success = false;
        }

        public ActionResult Index()
        {
            return View();

        }

        public ActionResult Test()
        {
            return View();
        }

        #region Treasury

        public ActionResult Get([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {
            try
            {
                var treasuries = _treasuryAppService.GetAllWithBalances().AsQueryable();

                var totalCount = treasuries.Count();

                // searching and sorting
                treasuries = SearchAndSort(requestModel, treasuries);
                var filteredCount = treasuries.Count();

                // Paging
                treasuries = treasuries.Skip(requestModel.Start).Take(requestModel.Length);

                var dataTablesResponse = new DataTablesResponse(requestModel.Draw, treasuries.ToList(), filteredCount, totalCount);
                return Json(dataTablesResponse, JsonRequestBehavior.AllowGet);
            }
            catch (BwrException ex)
            {
                Tracing.SaveException(ex);
                return Json(new { Success = false, Message = _message }, JsonRequestBehavior.AllowGet);
            }
        }


        [HttpGet]
        public ActionResult Create()
        {
            return View("_CreateTreasury");
        }

        [HttpPost]
        public ActionResult Create(TreasuryInsertDto dto)
        {
            var exist = false;
            if (!ModelState.IsValid)
            {

            }
            if (_treasuryAppService.CheckIfExist(dto.Name, 0))
            {
                _success = false;
                _message = "توجد صندوق بنفس الاسم";
                exist = true;
            }
            else
            {
                var treasuryDto = _treasuryAppService.Insert(dto);
                if (treasuryDto != null)
                    _success = true;
                else
                {
                    _success = false;
                    _message = "حدثت مشكلة اثناء إضافة بيانات الصندوق";
                }
            }

            return Json(new { Success = _success, Message = _message, Exist = exist }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var dto = _treasuryAppService.GetForEdit(id);

            if (Request.IsAjaxRequest())
                return PartialView("_EditTreasury", dto);

            return View(dto);
        }

        [HttpPost]
        public ActionResult Edit(TreasuryUpdateDto dto)
        {
            var exist = false;

            if (_treasuryAppService.CheckIfExist(dto.Name, dto.Id.Value))
            {
                _success = false;
                _message = "توجد صندوق بنفس الاسم";
                exist = true;
            }
            else
            {
                var treasuryDto = _treasuryAppService.Update(dto);
                if (treasuryDto != null)
                    _success = true;
                else
                {
                    _success = false;
                    _message = "حدثت مشكلة اثناء تعديل بيانات الصندوق";
                }
            }

            return Json(new { Success = _success, Message = _message, Exist = exist }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var dto = _treasuryAppService.GetById(id);

            if (Request.IsAjaxRequest())
                return PartialView("_DeleteTreasury", dto);

            return View(dto);
        }

        [HttpPost]
        public ActionResult Delete(TreasuryDto dto)
        {
            _treasuryAppService.Delete(dto.Id.Value);

            return Content("success");
        }

        #endregion

        #region Treasury Details

        public ActionResult Detail(int id)
        {
            var dto = _treasuryAppService.GetById(id);

            var coins = _coinAppService.GetAll();
            ViewBag.Coins = new SelectList(coins, "Id", "Name");

            return View("_DetailsTreasury", dto);
        }

        
        #endregion

        #region Helper Method

        private IQueryable<TreasurysDto> SearchAndSort(IDataTablesRequest requestModel, IQueryable<TreasurysDto> query)
        {
            // Apply filters
            if (requestModel.Search.Value != string.Empty)
            {
                var value = requestModel.Search.Value.Trim();
                query = query.Where(p => p.Name.Contains(value)

                                   );
            }

            var filteredCount = query.Count();

            // Sort
            var sortedColumns = requestModel.Columns.GetSortedColumns();
            var orderByString = string.Empty;

            foreach (var column in sortedColumns)
            {
                orderByString += orderByString != string.Empty ? "," : "";
                orderByString += (column.Data) + (column.SortDirection == Column.OrderDirection.Ascendant ? " asc" : " desc");
            }

            query = query.OrderBy(orderByString == string.Empty ? "BarCode asc" : orderByString);

            return query;
        }

        #endregion
    }
}

Bwr.WebApp/Controllers/Treasury/TreasuryMoneyActionController.cs
using BWR.Application.Common;
using BWR.Application.Dtos.Treasury.TreasuryMoneyAction;
using BWR.Application.Interfaces.TreasuryMoneyAction;
using System.Linq;
using System.Web.Mvc;

namespace Bwr.WebApp.Controllers.Treasury
{
    public class TreasuryMoneyActionController : Controller
    {
        private readonly ITreasuryMoneyActionAppService _treasuryMoneyActionAppService;
        private string _message;
        private bool _success;

        public TreasuryMoneyActionController(ITreasuryMoneyActionAppService treasuryMoneyActionAppService)
        {
            _treasuryMoneyActionAppService = treasuryMoneyActionAppService;
            _message = "";
            _success = false;
        }


        public ActionResult TreasuryBalance(int treasuryId)
        {
            TempData["TreasuryId"] = treasuryId.ToString();

            var treasuryMoneyActionInsertDto = new TreasuryMoneyActionInsertDto()
            {
                TreasuryId = treasuryId
            };
            return View(treasuryMoneyActionInsertDto);
        }

        public ActionResult TreasuryActions(int treasuryId)
        {
            var entityDto = new EntityDto()
            {
                Id = treasuryId
            };
            return View(entityDto);
        }

        // GET: TreasuryMoneyActionFlow
        public ActionResult Get(TreasuryMoneyActionInputDto input)
        {
            var treasuryMoneyActiones = _treasuryMoneyActionAppService.Get(input).OrderByDescending(x=>x.Id);
            return Json(new { data = treasuryMoneyActiones }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTreasuryActions(TreasuryMoneyActionInputDto input)
        {
            var treasuryActiones = _treasuryMoneyActionAppService.GetMoneyActions(input).OrderByDescending(x => x.Id);
            return Json(new { data = treasuryActiones }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Create(TreasuryMoneyActionInsertDto dto)
        {
            var treasuryId = 0;
            TreasuryMoneyActionDto treasuryMoneyActionDto;
            if (dto.ActionType == 1)
            {
                treasuryMoneyActionDto = _treasuryMoneyActionAppService.GetMony(dto);
            }
            else
            {
                treasuryMoneyActionDto = _treasuryMoneyActionAppService.GiveMony(dto);
            }
            if (treasuryMoneyActionDto != null)
            {
                _success = true;
                treasuryId = treasuryMoneyActionDto.TreasuryId;
            }
            else
            {
                _success = false;
                _message = "حدثت مشكلة اثناء إضافة البيانات";
            }

            return Json(new { Success = _success, Message = _message,TreasuryId= treasuryId }, JsonRequestBehavior.AllowGet);
        }

    }
}

Bwr.WebApp/Views/Treasury/_CreateTreasury.cshtml
@using BWR.Application.Dtos.Treasury

@model BWR.Application.Dtos.Treasury.TreasuryInsertDto
@{
    /**/

    Layout = null;
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">إضافة صندوق</h4>
        </div>
        @using (Ajax.BeginForm("Create", "Treasury", null, new AjaxOptions { HttpMethod = "Post" }, new { @class = "form-horizontal", role = "form", id = "addTreasuryForm" }))
        {
            <div class="modal-body ">
                <div class="col-lg-12 col-md-12">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item active">
                            <a class="nav-link active" id="treasury-tab" data-toggle="tab" href="#addTreasurySection" role="tab">بيانات الصندوق</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="provinces-tab" data-toggle="tab" href="#addCoinSection" role="tab">إضافة رصيد</a>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-12 col-md-12">
                    <div class="tab-content">
                        <div class="tab-pane active" id="addTreasurySection">
                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-group">
                                    <label class="control-label col-md-3" for="Name">اسم الصندوق <span class="text-danger">*</span></label>
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", id = "a-treasury-name" } })

                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                            </div>
                        </div>


                        <div class="tab-pane" id="addCoinSection">

                            <div class="row a-coins">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">

                        <button id="btnAddTreasury" type="button" class="btn btn-primary">حفظ <span class="glyphicon glyphicon-save"></span></button>
                        <button type="button" class="btn btn-sm btn-default" onclick="resetTreasuryContainer()" data-dismiss="modal">إغلاق <span class="glyphicon glyphicon-remove"></span></button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script>

    $(function () {

        initialCoins();

        var $form = $("#addTreasuryForm");
        $.validator.unobtrusive.parse($form);

        $('#btnAddTreasury').on("click", function (event) {
            if ($form.valid()) {

                var dto = {
                    Name: $('#a-treasury-name').val(),
                    TreasuryCashes: getCoins()
                };

                $.ajax({
                    url: '@Url.Action("Create", "Treasury")',
                    type: 'POST',
                    data: dto,
                    dataType: "json",
                    cache: false,
                    success: function (data) {

                        if (data.Success == true) {
                            resetTreasuryContainer();

                            $treasuryDataTable.refresh();
                            toastr.success('تم الحفظ بنجاح')
                        }
                        else {
                            if (data.Exist == true) {
                                $('[data-valmsg-for="Name"]').html("");
                                $('[data-valmsg-for="Name"]').html(data.Message);
                            }
                            toastr.error(data.Message);
                        }

                    },
                    error: function () { toastr.error("خدث خطأ ما أثناء الإضافة"); }
                });

            }


        });

    });


    function getCoins() {
        
        var treasuryCoins = [];
        var coinInputs = $('.a-coins-inputs');
        for (var i = 0; i < coinInputs.length ; i++) {
            var id = $(coinInputs[i]).attr('data-coin-id');
            var value = $(coinInputs[i]).val();

            treasuryCoins.push({ 'InitialBalance': value, 'Total': value, 'CoinId': id });
        }

        return treasuryCoins;
    }


    function initialCoins() {
        $.get('@Url.Action("GetCoinsForDropdown","Coin")', { term: "" }, function (data) {

            var coins = data.Coins;
            for (var i = 0; i < coins.length; i++) {
                var ele = '<div class="form-group">' +
                    '<label class="control-label col-md-3 col-sm-3">' + coins[i].Name + ':</label>' +
                    '<div class="col-md-8 col-sm-8">' +
                    '<div class="input-group">' +
                    '<input  type="number" data-coin-id="' + coins[i].Id+'" class="form-control a-coins-inputs" value="0" />' +
                    '<span class="input-group-addon">' + coins[i].Code + '</span>' +

                    '</div>' +
                    '</div>' +
                    '</div>';

                $('.a-coins').append(ele);
            }

        });
    }

    function resetTreasuryContainer() {

        $('#createTreasuryModal').modal('hide');
        $('#createTreasuryContainer').html('');
    }


</script>

Bwr.WebApp/Views/Treasury/_DeleteTreasury.cshtml
@model BWR.Application.Dtos.Treasury.TreasuryDto
@{
    Layout = null;
}

<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">حذف صندوق</h4>
        </div>
        @using (Ajax.BeginForm("Delete", "Treasury", null, new AjaxOptions { HttpMethod = "Post", OnSuccess = "deleteTreasurySuccess" }, new { @class = "form-horizontal", role = "form" }))
        {
            <div class="modal-body">
                <div class="form-horizontal">
                    @Html.HiddenFor(model => model.Id)
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <a href="#"><h4>هل انت متأكد من حذف هذا الصندوق <span class="badge">@Model.Name</span></h4></a>
                    <br />
                    <div class="alert alert-danger">
                        <strong>ملاحظة!</strong> لايمكن حذف صندوق مرتبط بعمليات
                    </div>

                </div>
            </div>
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-danger">حذف <span class="glyphicon glyphicon-trash"></span></button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">إغلاق <span class="glyphicon glyphicon-remove"></span></button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Bwr.WebApp/Views/Treasury/_DetailsTreasury.cshtml
@model BWR.Application.Dtos.Treasury.TreasuryDto
@{
    ViewBag.Title = "الصندوق";
    Layout = "~/Views/Shared/_BlankPageLayout.cshtml";
}


@section  Style{
    <!--Data Table Style-->
    <link href="~/Content/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap-rtl.css" rel="stylesheet"
          type="text/css" />
    <!--End Data Table Style-->
    <!--Begin Css Jquery Confirm-->
    <link href="~/Content/Jquery-Confirm/Jquery-confrim-css.css" rel="stylesheet" />
    <!--END Css Jquery Confirm-->

}

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN PROFILE SIDEBAR -->
        <div class="profile-sidebar">
        </div>
        <!-- END BEGIN PROFILE SIDEBAR -->
        <!-- BEGIN PROFILE CONTENT -->
        <div class="profile-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet light ">
                        <div class="portlet-title tabbable-line">
                            <div class="caption caption-md">
                                <i class="icon-globe theme-font hide"></i>
                                <span class="caption-subject font-blue-madison bold uppercase"> الصندوق: @Model.Name  </span>
                            </div>
                            <ul class="nav nav-tabs">
                                <li class="active">
                                    <a href="#currentBalance" data-toggle="tab" aria-expanded="true">الرصيد الحالي</a>
                                </li>

                                <li>
                                    <a href="#treasuryBalance" data-url="@Url.Action("TreasuryBalance","TreasuryMoneyAction")?treasuryId=@Model.Id" data-toggle="tab">كشف حساب الصندوق </a>
                                </li>
                                <li>
                                    <a href="#treasuryActions" data-url="@Url.Action("TreasuryActions","TreasuryMoneyAction")?treasuryId=@Model.Id" data-toggle="tab">كشف حركات الصندوق </a>
                                </li>
                            </ul>
                        </div>
                        <div class="portlet-body">
                            <div class="tab-content">
                                <!-- PERSONAL INFO TAB -->
                                <div class="tab-pane active" id="currentBalance">
                                    <div class="portlet box green">
                                        <div class="portlet-title">
                                            <div class="caption">

                                            </div>
                                            <div class="tools"> </div>
                                        </div>
                                        <div class="portlet-body">

                                            <div class="row">
                                                <div class="col-lg-12 col-md-12">
                                                    <table class="table table-actions-wrapper" id="treasuryBalanceDataTable"></table>

                                                </div>

                                            </div>
                                        </div>

                                    </div>

                                </div>
                                <div class="tab-pane" id="treasuryBalance"></div>
                                <div class="tab-pane" id="treasuryActions"></div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END PROFILE CONTENT -->
    </div>
</div>

<script>
    $(function () {
        var $treasuryBalanceDataTable;
        $('input.flat').iCheck({
            checkboxClass: 'icheckbox_flat-green',
            radioClass: 'iradio_flat-green'
        });
        var treasuryId = '@Model.Id';

        $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
            var url = $(e.target).attr('data-url');
            debugger;
            if (url == null) {
                $treasuryBalanceDataTable.refresh();
            }
            
            var id = e.target.href.split("#")[1];
            $('#' + id).load(url);
        });

        $treasuryBalanceDataTable = {
                    dt: null,
                    init: function () {
                        dt = $('#treasuryBalanceDataTable').DataTable({
                            'language': dataTableLocalizationArValue(),
                            'ajax': {
                                'url': '@Url.Action("Get", "TreasuryCash")',
                                'method': 'POST',
                                'data': {'treasuryId':'@Model.Id'},
                            },
                            'columns': [
                                { 'title': 'العملة', 'data': 'Coin.Name',  'searchable': true },

                                {'title': 'له','data': "Total",'searchable': true,
                                    render: function (data, type, row) {
                                        if (data > 0) {
                                            return data;
                                        } else {
                                            return '';
                                        }
                                    },
                                },
                                {'title': 'عليه','data': "Total",'searchable': true,
                                    render: function (data, type, row) {
                                        if (data < 0) {
                                            return data * -1;
                                        } else {
                                            return '';
                                        }
                                    },
                                }

                            ],
                            'lengthMenu': [10, 25, 50, 100],
                        });
                    },

                refresh: function () {

                    dt.ajax.reload();
                    }
                }

            $treasuryBalanceDataTable.init();

    });
</script>